### ISSUE TITLE
ghidra api usage error

### ISSUE THREAD

**Issue by SteinsGatep001** [al3xtjames/ghidra-firmware-utils#23]
Code
```Java
BinaryReader reader = new BinaryReader(new ByteArrayProvider(blockBytes), true);
// ....
NTHeader ntHeader = new NTHeader(reader, ntHeaderOffset, PortableExecutable.SectionLayout.FILE, false, false);
```
should be changed to
```Java
FactoryBundledWithBinaryReader reader = new FactoryBundledWithBinaryReader(RethrowContinuesFactory.INSTANCE, new ByteArrayProvider(blockBytes), true);
// ...
NTHeader ntHeader = NTHeader.createNTHeader(reader, ntHeaderOffset, PortableExecutable.SectionLayout.FILE, false, false);
```
Tested in Ghidra 10.1.5

**Comment by al3xtjames** [comment]
This was done in https://github.com/al3xtjames/ghidra-firmware-utils/commit/b07081698df6320c8fae9f96dba07f43b27071aa, which was included in [20221104.1](https://github.com/al3xtjames/ghidra-firmware-utils/releases/tag/20221104.1). 20221104.1 is just [20221104.0](https://github.com/al3xtjames/ghidra-firmware-utils/releases/tag/20221104.0) with API updates for Ghidra 10.2, so you can use 20221104.0 on Ghidra 10.1.5.
