### ISSUE TITLE
why i dl the zip file in the releases is missing the gradlew but if i dl zip in the code green button it have the gradlew file thx

### ISSUE THREAD

**Issue by kocoman2** [al3xtjames/ghidra-firmware-utils#26]
why i dl the zip file in the releases is missing the gradlew but if i dl zip in the code green button it have the gradlew file thx

**Comment by al3xtjames** [comment]
Which archive are you downloading? `ghidra_10.3.1_PUBLIC_20230621.0_ghidra-firmware-utils.zip` is a compiled plugin, which is why the Gradle build scripts aren't present. The `Source code (zip)` and `Source code (tar.gz)` archives should contain `gradlew`.
