### ISSUE TITLE
JRE compatibility between ghidra und firmware utils

### ISSUE THREAD

**Issue by ubfx** [al3xtjames/ghidra-firmware-utils#5]
The ghidra client for shared projects works only with JREs up to JRE 11.

So if the firmware utils should be used for collaborative projects, one has to make sure to build it with the same JRE, that ghidra runs on (by setting JAVA_HOME environment variable for gradle).

Maybe this should be mentioned in the readme

**Comment by al3xtjames** [comment]
Thanks, I'll add this to the README.
