### ISSUE TITLE
UEFIFirmwareVolumeHeader field sizes documentation

### ISSUE THREAD

**Issue by dev747368** [al3xtjames/ghidra-firmware-utils#7]
Is the size for "Reset Vector" in the "UEFI Firmware Volume Header" part of the javadoc incorrect?

It currently shows as 1, but the code in the ctor that reads the data is reading a 16 byte array into zeroVector.

Also, some of the magic constants sprinkled around (ie. position - 40) make sense if you are calculating the position of the start of the volume header if the size for that field is 16 and not 1.

**Comment by al3xtjames** [comment]
Good catch, the reset vector in the firmware volume header is indeed 16 bytes long.

**Comment by dev747368** [comment]
Cool.  FYI, would you be receptive to a pull request that tweaks the way you are doing GFileSystem stuff?  You choose to copy the old-style implementation that I'm working on stamping out of the code base.

**Comment by dev747368** [comment]
Also, do you have some pointers to sample files for these file systems?

**Comment by al3xtjames** [comment]
I'd appreciate such a PR, thanks. I've attached some random UEFI images that I used to test my implementation (by comparing with [UEFITool](https://github.com/LongSoft/UEFITool)):

[fw.zip](https://github.com/al3xtjames/ghidra-firmware-utils/files/4390578/fw.zip)

**Comment by al3xtjames** [comment]
Forgot to ask this earlier: do you have an example of a new-style GFileSystem implementation?

**Comment by dev747368** [comment]
Basically anything that comes directly from the GFileSystem interface instead of GFileSystemBase.
The zip, tar and coff archive file systems are pretty good representations.
